name: CI
on:
- push
jobs:
  xenial:
    container: 
      image: vapor/swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --enable-test-discovery
  bionic:
    container: 
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --enable-test-discovery